# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Corne/Documents/MEGA/4. Semester/Semesterprojekt/Semesterprojekt_4/FPGA_projekt/PYNQ-Z2_v1.0.xdc

# Block Designs: bd/test_sync/test_sync.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_sync || ORIG_REF_NAME==test_sync} -quiet] -quiet

# IP: bd/test_sync/ip/test_sync_flipflipflopflop_0_0/test_sync_flipflipflopflop_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_sync_flipflipflopflop_0_0 || ORIG_REF_NAME==test_sync_flipflipflopflop_0_0} -quiet] -quiet

# IP: bd/test_sync/ip/test_sync_flipflipflopflop_0_1/test_sync_flipflipflopflop_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_sync_flipflipflopflop_0_1 || ORIG_REF_NAME==test_sync_flipflipflopflop_0_1} -quiet] -quiet

# XDC: c:/Users/Corne/Documents/MEGA/4. Semester/Semesterprojekt/Semesterprojekt_4/FPGA_projekt/FPGA_projekt.gen/sources_1/bd/test_sync/test_sync_ooc.xdc
