# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/jacob/Documents/Semester4/Semesterprojekt_4/FPGA_projekt/PYNQ-Z2_v1.0.xdc

# Block Designs: bd/buildup/buildup.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup || ORIG_REF_NAME==buildup} -quiet] -quiet

# IP: bd/buildup/ip/buildup_xlconstant_1_0/buildup_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_xlconstant_1_0 || ORIG_REF_NAME==buildup_xlconstant_1_0} -quiet] -quiet

# IP: bd/buildup/ip/buildup_clock_divider_0_0/buildup_clock_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_clock_divider_0_0 || ORIG_REF_NAME==buildup_clock_divider_0_0} -quiet] -quiet

# IP: bd/buildup/ip/buildup_xlconcat_0_0/buildup_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_xlconcat_0_0 || ORIG_REF_NAME==buildup_xlconcat_0_0} -quiet] -quiet

# IP: bd/buildup/ip/buildup_xlslice_0_0/buildup_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_xlslice_0_0 || ORIG_REF_NAME==buildup_xlslice_0_0} -quiet] -quiet

# IP: bd/buildup/ip/buildup_xlslice_1_0/buildup_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_xlslice_1_0 || ORIG_REF_NAME==buildup_xlslice_1_0} -quiet] -quiet

# IP: bd/buildup/ip/buildup_counter_1_0/buildup_counter_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_counter_1_0 || ORIG_REF_NAME==buildup_counter_1_0} -quiet] -quiet

# IP: bd/buildup/ip/buildup_xlslice_2_0/buildup_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_xlslice_2_0 || ORIG_REF_NAME==buildup_xlslice_2_0} -quiet] -quiet

# IP: bd/buildup/ip/buildup_xlslice_2_1/buildup_xlslice_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_xlslice_2_1 || ORIG_REF_NAME==buildup_xlslice_2_1} -quiet] -quiet

# IP: bd/buildup/ip/buildup_pwm_gen_0_2/buildup_pwm_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_pwm_gen_0_2 || ORIG_REF_NAME==buildup_pwm_gen_0_2} -quiet] -quiet

# IP: bd/buildup/ip/buildup_pwm_gen_0_3/buildup_pwm_gen_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_pwm_gen_0_3 || ORIG_REF_NAME==buildup_pwm_gen_0_3} -quiet] -quiet

# IP: bd/buildup/ip/buildup_AND_gate_0_0/buildup_AND_gate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_AND_gate_0_0 || ORIG_REF_NAME==buildup_AND_gate_0_0} -quiet] -quiet

# IP: bd/buildup/ip/buildup_AND_gate_0_1/buildup_AND_gate_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_AND_gate_0_1 || ORIG_REF_NAME==buildup_AND_gate_0_1} -quiet] -quiet

# IP: bd/buildup/ip/buildup_AND_gate_0_2/buildup_AND_gate_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_AND_gate_0_2 || ORIG_REF_NAME==buildup_AND_gate_0_2} -quiet] -quiet

# IP: bd/buildup/ip/buildup_AND_gate_0_3/buildup_AND_gate_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_AND_gate_0_3 || ORIG_REF_NAME==buildup_AND_gate_0_3} -quiet] -quiet

# IP: bd/buildup/ip/buildup_NOT_gate_0_0/buildup_NOT_gate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_NOT_gate_0_0 || ORIG_REF_NAME==buildup_NOT_gate_0_0} -quiet] -quiet

# IP: bd/buildup/ip/buildup_NOT_gate_0_1/buildup_NOT_gate_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_NOT_gate_0_1 || ORIG_REF_NAME==buildup_NOT_gate_0_1} -quiet] -quiet

# IP: bd/buildup/ip/buildup_spi_sub_0_0/buildup_spi_sub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_spi_sub_0_0 || ORIG_REF_NAME==buildup_spi_sub_0_0} -quiet] -quiet

# IP: bd/buildup/ip/buildup_synchronizer_0_2/buildup_synchronizer_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_synchronizer_0_2 || ORIG_REF_NAME==buildup_synchronizer_0_2} -quiet] -quiet

# IP: bd/buildup/ip/buildup_synchronizer_0_3/buildup_synchronizer_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_synchronizer_0_3 || ORIG_REF_NAME==buildup_synchronizer_0_3} -quiet] -quiet

# IP: bd/buildup/ip/buildup_synchronizer_0_4/buildup_synchronizer_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_synchronizer_0_4 || ORIG_REF_NAME==buildup_synchronizer_0_4} -quiet] -quiet

# IP: bd/buildup/ip/buildup_synchronizer_0_5/buildup_synchronizer_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_synchronizer_0_5 || ORIG_REF_NAME==buildup_synchronizer_0_5} -quiet] -quiet

# IP: bd/buildup/ip/buildup_synchronizer_0_6/buildup_synchronizer_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_synchronizer_0_6 || ORIG_REF_NAME==buildup_synchronizer_0_6} -quiet] -quiet

# IP: bd/buildup/ip/buildup_synchronizer_0_7/buildup_synchronizer_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_synchronizer_0_7 || ORIG_REF_NAME==buildup_synchronizer_0_7} -quiet] -quiet

# IP: bd/buildup/ip/buildup_synchronizer_0_8/buildup_synchronizer_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_synchronizer_0_8 || ORIG_REF_NAME==buildup_synchronizer_0_8} -quiet] -quiet

# IP: bd/buildup/ip/buildup_synchronizer_0_9/buildup_synchronizer_0_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_synchronizer_0_9 || ORIG_REF_NAME==buildup_synchronizer_0_9} -quiet] -quiet

# IP: bd/buildup/ip/buildup_synchronizer_0_10/buildup_synchronizer_0_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_synchronizer_0_10 || ORIG_REF_NAME==buildup_synchronizer_0_10} -quiet] -quiet

# IP: bd/buildup/ip/buildup_synchronizer_0_11/buildup_synchronizer_0_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_synchronizer_0_11 || ORIG_REF_NAME==buildup_synchronizer_0_11} -quiet] -quiet

# IP: bd/buildup/ip/buildup_Rising_edge_detector_0_0/buildup_Rising_edge_detector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_Rising_edge_detector_0_0 || ORIG_REF_NAME==buildup_Rising_edge_detector_0_0} -quiet] -quiet

# IP: bd/buildup/ip/buildup_Falling_edge_detector_0_0/buildup_Falling_edge_detector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_Falling_edge_detector_0_0 || ORIG_REF_NAME==buildup_Falling_edge_detector_0_0} -quiet] -quiet

# IP: bd/buildup/ip/buildup_xlslice_5_0/buildup_xlslice_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_xlslice_5_0 || ORIG_REF_NAME==buildup_xlslice_5_0} -quiet] -quiet

# IP: bd/buildup/ip/buildup_block_encoder_0_3/buildup_block_encoder_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_block_encoder_0_3 || ORIG_REF_NAME==buildup_block_encoder_0_3} -quiet] -quiet

# IP: bd/buildup/ip/buildup_block_encoder_0_4/buildup_block_encoder_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==buildup_block_encoder_0_4 || ORIG_REF_NAME==buildup_block_encoder_0_4} -quiet] -quiet

# XDC: /home/jacob/Documents/Semester4/Semesterprojekt_4/FPGA_projekt/FPGA_projekt.gen/sources_1/bd/buildup/buildup_ooc.xdc
