# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Corne/Documents/MEGA/4. Semester/Semesterprojekt/Semesterprojekt_4/FPGA_projekt/FPGA_projekt.srcs/sources_1/bd/buildup/ip/buildup_block_encoder_pan_0_0/buildup_block_encoder_pan_0_0.xci
# IP: The module: 'buildup_block_encoder_pan_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Corne/Documents/MEGA/4. Semester/Semesterprojekt/Semesterprojekt_4/FPGA_projekt/FPGA_projekt.gen/sources_1/bd/buildup/ip/buildup_block_encoder_pan_0_0/src/block_encoder_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'buildup_block_encoder_pan_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Corne/Documents/MEGA/4. Semester/Semesterprojekt/Semesterprojekt_4/FPGA_projekt/FPGA_projekt.srcs/sources_1/bd/buildup/ip/buildup_block_encoder_pan_0_0/buildup_block_encoder_pan_0_0.xci
# IP: The module: 'buildup_block_encoder_pan_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Corne/Documents/MEGA/4. Semester/Semesterprojekt/Semesterprojekt_4/FPGA_projekt/FPGA_projekt.gen/sources_1/bd/buildup/ip/buildup_block_encoder_pan_0_0/src/block_encoder_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'buildup_block_encoder_pan_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
