# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jacob/Documents/Semester4/Semesterprojekt_4/FPGA_projekt/FPGA_projekt.srcs/sources_1/bd/encoder_test/ip/encoder_test_block_encoder_0_0/encoder_test_block_encoder_0_0.xci
# IP: The module: 'encoder_test_block_encoder_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jacob/Documents/Semester4/Semesterprojekt_4/FPGA_projekt/FPGA_projekt.gen/sources_1/bd/encoder_test/ip/encoder_test_block_encoder_0_0/src/block_encoder_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'encoder_test_block_encoder_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/jacob/Documents/Semester4/Semesterprojekt_4/FPGA_projekt/FPGA_projekt.srcs/sources_1/bd/encoder_test/ip/encoder_test_block_encoder_0_0/encoder_test_block_encoder_0_0.xci
# IP: The module: 'encoder_test_block_encoder_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jacob/Documents/Semester4/Semesterprojekt_4/FPGA_projekt/FPGA_projekt.gen/sources_1/bd/encoder_test/ip/encoder_test_block_encoder_0_0/src/block_encoder_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'encoder_test_block_encoder_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
